add 2 task
js-tasks-ru/js-20220909_artem97 pull request #2
Opened 2022-09-15 14:27 UTC by laPavlov

2022-09-15 14:28 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-15 22:52 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let newArr = Array.from(arr)
`const copy = [...arr]` - более современный способ скопировать массив

2022-09-15 22:52 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    if (param === 'asc') {
устраните дубликаты кода!

2022-09-15 22:52 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    if (fields.indexOf(key) !== -1) {
подумайте, может лучше подойдет метод `includes` вместо `indexOf`?

2022-09-15 22:53 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-09-18 09:42 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-18 10:10 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-18 10:14 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-18 10:25 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-18 10:34 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-09-19 13:08 UTC, dosandk approved these changes
good 👍

2022-09-19 13:08 UTC, merged